Repository onyx-dot-app/onyx, pull requests merged in 2025-07, with the labels that each got.

#5006 fix: Have document show up before message starts streaming back
  web/src/app/chat/ChatPage.tsx
Labels: fix

#5041 fix: Move around group-sync tests (since they require docker services to be running)
  .github/workflows/pr-external-dependency-unit-tests.yml
  .github/workflows/pr-python-connector-tests.yml
  backend/tests/daily/conftest.py
  backend/tests/external_dependency_unit/connectors/confluence/conftest.py
  backend/tests/external_dependency_unit/connectors/confluence/test_confluence_group_sync.py
  backend/tests/external_dependency_unit/connectors/google_drive/test_google_drive_group_sync.py
Labels: fix

#5040 feat: remove chat session necessity from send message simple api
  backend/ee/onyx/server/query_and_chat/chat_backend.py
  backend/ee/onyx/server/query_and_chat/models.py
Labels: feat

#5046 fix: improve support for non-default postgres schemas
  backend/alembic/env.py
  backend/alembic/versions/36e9220ab794_update_kg_trigger_functions.py
  backend/alembic/versions/495cb26ce93e_create_knowlege_graph_tables.py
  backend/onyx/db/engine/async_sql_engine.py
  backend/onyx/db/engine/sql_engine.py
  backend/onyx/kg/clustering/clustering.py
  backend/onyx/kg/clustering/normalizations.py
  backend/shared_configs/configs.py
Labels: fix

#5047 fix: improve assistant fetching efficiency
  web/src/app/ee/admin/performance/usage/PersonaMessagesChart.tsx
  web/src/app/ee/admin/performance/usage/page.tsx
  web/src/app/layout.tsx
  web/src/components/context/AppProvider.tsx
  web/src/components/context/AssistantsContext.tsx
  web/src/lib/chat/fetchAssistantdata.ts
Labels: fix

#5048 feat: KG improvements
  backend/onyx/agents/agent_search/kb_search/nodes/a3_generate_simple_sql.py
  backend/onyx/db/kg_temp_view.py
Labels: feat

#4974 feat: Search and Answer Quality Test Script
  backend/onyx/chat/process_message.py
  backend/tests/regression/search_quality/README.md
  backend/tests/regression/search_quality/models.py
  backend/tests/regression/search_quality/run_search_eval.py
  backend/tests/regression/search_quality/search_eval_config.yaml.template
  backend/tests/regression/search_quality/test_queries.json.template
  backend/tests/regression/search_quality/util_config.py
  backend/tests/regression/search_quality/util_data.py
  backend/tests/regression/search_quality/util_eval.py
  backend/tests/regression/search_quality/util_retrieve.py
  backend/tests/regression/search_quality/utils.py
Labels: feat

#5044 feat: Updated KG admin page
  backend/onyx/db/entities.py
  backend/onyx/db/entity_type.py
  backend/onyx/server/kg/api.py
  backend/onyx/server/kg/models.py
  backend/tests/integration/tests/kg/test_kg_api.py
  web/src/app/admin/connector/[ccPairId]/unused.txt
  web/src/app/admin/kg/KGEntityTypes.tsx
  web/src/app/admin/kg/interfaces.ts
  web/src/app/admin/kg/page.tsx
  web/src/app/admin/kg/utils.ts
  web/src/components/CollapsibleCard.tsx
  web/src/components/ui/dataTable.tsx
  web/src/components/ui/datePicker.tsx
  web/tailwind-themes/tailwind.config.js
Labels: feat

#5051 fix: Fix Teams connector failing when `from_.user` is not specified
  backend/onyx/connectors/teams/connector.py
  backend/onyx/connectors/teams/models.py
Labels: fix

#5062 refactor: Update error message when PR title fails validation
  .github/workflows/pr-labeler.yml
  .github/workflows/pr-labeller.yml
Labels: refactor

#5056 fix: time discrepancy
  .vscode/launch.template.jsonc
  backend/onyx/background/celery/tasks/docprocessing/tasks.py
  backend/onyx/server/documents/connector.py
Labels: fix

#5061 fix: remove extra group sync
  backend/onyx/background/celery/tasks/beat_schedule.py
Labels: fix
